name: Publish to docker registry

on:
  push:
    branches:
      - typescript
    paths:
      - 'package.json'
      - 'src/**'
      - 'docker/**'

jobs:
  publish:
    if: github.repository == 'CUP-ACM-Programming-Club/CUP-Online-Judge-Express'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Use Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build env
        run: |
          echo "::set-env name=PKG_VERSION::$(node script/get_version.js)"
      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: ryanlee2014/cupoj-backend
          tag: ${{ env.PKG_VERSION }}
          registry: docker.io
          dockerfile: ./docker/backend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: ryanlee2014/cupoj-websocket
          tag: ${{ env.PKG_VERSION }}
          registry: docker.io
          dockerfile: ./docker/websocket/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
