name: Publish to docker registry

on:
  push:
    branches:
      - typescript
      - master
      - main
    paths:
      - 'package.json'
      - 'src/**'
      - 'docker/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - typescript
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test:unit

  publish:
    needs: test
    if: github.event_name == 'push' && github.repository == 'CUP-ACM-Programming-Club/CUP-Online-Judge-Express'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Build env
        run: |
          echo "PKG_VERSION=$(node script/get_version.js)" >> $GITHUB_ENV
          echo "BACKEND_ENV_VERSION=$(cat docker/base/VERSION)" >> $GITHUB_ENV
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build Backend service image
        with:
          image: ryanlee2014/cupoj-backend-env
          tag: ${{ env.BACKEND_ENV_VERSION }}
          registry: docker.io
          dockerfile: ./docker/base/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build Backend service image
        with:
          image: ryanlee2014/cupoj-backend
          tag: ${{ env.PKG_VERSION }}
          registry: docker.io
          dockerfile: ./docker/backend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Update Backend service image
        with:
          image: ryanlee2014/cupoj-backend
          tag: latest
          registry: docker.io
          dockerfile: ./docker/backend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build Websocket service image
        with:
          image: ryanlee2014/cupoj-websocket
          tag: ${{ env.PKG_VERSION }}
          registry: docker.io
          dockerfile: ./docker/websocket/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Update latest image
        with:
          image: ryanlee2014/cupoj-websocket
          tag: latest
          registry: docker.io
          dockerfile: ./docker/websocket/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
